# Generated by Django 3.1.4 on 2020-12-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=150)),
                ('marca', models.CharField(max_length=150)),
                ('ano', models.IntegerField(max_length=4)),
                ('valor', models.FloatField(max_length=20)),
            ],
        ),
    ]
